server:
  port: 8880
spring:
  application:
    name: tccVerify-user
  datasource:
    # 数据存放在 当前目录/H2_DB/xxxx
    url: jdbc:h2:./H2_DB/user;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #    url: jdbc:mysql://1haoji:53306/tcc_verify_user
    username: sa
    password:
    #    type: com.zaxxer.hikari.HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
#org:
#  bytesoft:
#    bytetcc:
#      datasource:
#        autoconfig: false