spring:
  datasource:
    driver-class-name: org.h2.Driver
    # 数据存放在 当前目录/H2_DB/xxxx
    url: jdbc:h2:./H2_DB/order;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    type: com.zaxxer.hikari.HikariDataSource
    username: sa
    password:

org:
  dromara:
    hmily:
      started: true