management:
  endpoint:
    health:
      show-details: always

# SpringCloud feign 默认开启支持ribbon
ribbon:
  # 请求连接的超时时间
  ConnectTimeout: 1000
  # 请求处理的超时时间
  ReadTimeout: 2000
  # 对当前实例的重试次数
  MaxAutoRetries: 2
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    # 默认
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            # 断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
            timeoutInMilliseconds: 8000

###开启Hystrix断路器
feign:
  hystrix:
    enabled: true

spring:
  aop:
    auto: true
  main:
    allow-bean-definition-overriding: true
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # 自动更新表结构
      ddl-auto: update
    properties:
      hibernate:
        # 在控制台打出sql
        show_sql: true
#  h2:
#    console:
#      enabled: true
#      # 访问H2控制台的路径
#      path: /h2/console
#      settings:
#        trace: false
#        # 远程访问控制台
#        web-allow-others: true

org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 30
      retryMax: 30
      scheduledDelay: 30
      scheduledThreadMax:  10
      repositorySupport: db
      hmilyDbConfig:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://2haoji:3306/tcc_verify_hmily?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: admin

logging:
  level:
    root: info
    org.springframework: debug
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.dromara.hmily.bonuspoint: debug
    org.dromara.hmily.lottery: debug
    org.dromara.hmily: debug
    io.netty: info